# NO 'user' directive here when master is non-root
worker_processes  4;                      # fissi, no autotune
pid              /tmp/nginx/nginx.pid;    # scrivibile da non-root

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Log su stdout/stderr per container
    access_log  /dev/stdout;
    error_log   /dev/stderr  warn;

    # Temp paths in /tmp (sempre scrivibili)
    client_body_temp_path /tmp/nginx/client_temp 1 2;
    proxy_temp_path       /tmp/nginx/proxy_temp;
    fastcgi_temp_path     /tmp/nginx/fastcgi_temp;
    uwsgi_temp_path       /tmp/nginx/uwsgi_temp;
    scgi_temp_path        /tmp/nginx/scgi_temp;

    # Gzip global
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 1024;
    gzip_vary on;
    gzip_proxied any;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        application/xml
        application/rss+xml
        image/svg+xml;

    include /etc/nginx/conf.d/*.conf;
}
